repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.4.4'
    hooks:
      - id: autopep8
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.9'
    hooks:
      - id: flake8
        args: ['--max-line-length=120']
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.1.1a5
    hooks:
      - id: ansible-lint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.16.0
    hooks:
      - id: yamllint
        # pre-commit only reads .yamllint
        args: [--config-file=.yamllint.yaml]
