---
# Prepare home node for connecting (keys)
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Generate ssh key if does not exist
      openssh_keypair:
        path: './files/cluster-ssh-key'
        size: 4096
      tags: never, setupkeys
    - name: Add IAAS nodes from hosts.txt to Ansible inventory
      add_host:
        hostname: "{{ item.split('@')[1].split(':')[0] if '@' in item else item.split('/')[1].split(':')[0] }}"
        ansible_user: ubuntu
        groups: ["all", "nodes"]
      with_lines: cat ./hosts.txt
      tags: push, pull
    - name: Push data
      include: includes/push.yaml
      tags: never, push

# Prepare IAAS nodes
- hosts: all
  become: yes
  connection: ssh
  gather_facts: true
  tasks:
    - name: Set authorized key
      authorized_key:
        user: ubuntu
        key: '{{ item }}'
        state: present
      with_file:
        - './cluster-ssh-key.pub'
      tags: never, setupkeys
    - name: Setup environment
      include: includes/environment.yaml
    - name: Setup python packages from files/requirements.txt
      include: includes/python.yaml
    - name: Setup bcftools
      include: includes/bcftools.yaml
    - name: Pull results
      include: includes/pull.yaml
      tags: never, pull
    - name: Synchronize scripts
      synchronize:
        src: './scripts'
        dest: /home/ubuntu/
