---
# Prepare home node for connecting (keys)
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Generate ssh key if does not exist
      openssh_keypair:
        path: './files/cluster-ssh-key'
        size: 4096
      tags: never, setupkeys
    - name: Add IAAS nodes from hosts.txt to Ansible inventory
      add_host:
        hostname: "{{ item.split('@')[1].split(':')[0] if '@' in item else item.split('/')[1].split(':')[0] }}"
        ansible_user: ubuntu
        groups: ["all", "nodes"]
      with_lines: cat ./hosts.txt
      tags: always

# Prepare IAAS nodes
- hosts: all
  become: yes
  connection: ssh
  gather_facts: true
  tasks:
    - name: Setup environment
      include: includes/environment.yaml
    - name: Setup python packages from files/requirements.txt
      include: includes/python.yaml

- hosts: all
  become: no
  connection: ssh
  gather_facts: false
  tasks:
    - name: Cleanup Results
      file:
        dest: "/home/ubuntu/results"
        state: absent
        mode: '0755'
      tags: never, cleanresults
    - name: Cleanup data
      file:
        dest: "/home/ubuntu/data"
        state: absent
        mode: '0755'
      tags: never, cleandata
    - name: Setup folders
      include: includes/folders.yaml
      tags: cleandata, cleanresults
    - name: Pull results
      include: includes/pull_results.yaml
      tags: never, pull
    - name: Synchronize scripts
      synchronize:
        src: './code/'
        dest: /home/ubuntu/code/

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Push data
      include: includes/push_data.yaml
      tags: never, push
