---
ansible_connection: ssh
ansible_user: ubuntu
remote_code_path: ~/bluebox
remote_data_path: ~/bluebox/data
remote_results_path: ~/bluebox/results
local_code_path: ../code
local_data_path: ../data
local_results_path: ../results
