---
# Prepare home node for connecting (keys)
- hosts: localhost
  connection: local
  pre_tasks:
  - name: Make sure pip, parallel and sshpass packages are installed
    raw:
      if [ test -e /usr/bin/apt-get ]; then
          sudo apt-get -qqy update;
          sudo apt-get install -qqy python3 sshpass parallel python3-venv python3-pip uuid pssh;
      fi
    register: output
    changed_when: output.stdout != ""
    ignore_errors: yes
  tasks:
    - name: Setup local dependencies
      include: includes/localhost.yaml
      tags: always
    - name: Generate ssh key if does not exist
      openssh_keypair:
        path: 'files/{{ ansible_user_id }}-ssh-key'
        size: 4096
      tags: setupkeys
    - name: "Add IAAS nodes from {{ hosts_path | default('hosts.txt') }} to Ansible inventory"
      add_host:
        hostname: "{{ item.split('@')[1].split(':')[0] if '@' in item else item.split('/')[1].split(':')[0] }}"
        ansible_user: "{{ ansible_user_id }}"
        ansible_ssh_user: "{{ ansible_user_id }}"
        ansible_ssh_private_key_file: "files/{{ ansible_user_id }}-ssh-key"
        local_lab_user: "{{ ansible_user_id }}"
        ansible_python_interpreter: "/usr/bin/python3"
        groups: ["all", "nodes"]
      ignore_errors: yes
      with_lines: "cat ../{{ hosts_path | default('hosts.txt') }}"
      tags: always
    - name: "Add IAAS nodes from {{ hosts_path | default('hosts.txt') }} to Ansible inventory"
      add_host:
        hostname: "{{ item.split('@')[1].split(':')[0] if '@' in item else item.split('/')[1].split(':')[0] }}"
        ansible_user: ubuntu
        ansible_ssh_user: ubuntu
        ansible_ssh_pass: ubuntu
        local_lab_user: "{{ ansible_user_id }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o IdentitiesOnly=yes"
        ansible_python_interpreter: "/usr/bin/python3"
        # ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null -o PasswordAuthentication=yes"
        groups: ["presetup"]
      ignore_errors: yes
      with_lines: "cat ../{{ hosts_path | default('hosts.txt') }}"
      tags: setupkeys

# Prepare IAAS nodes
- hosts: presetup
  tasks:
    - name: Ensure groups exist
      become: yes
      group:
        name: "{{ item }}"
        state: present
      ignore_errors: yes
      with_items:
        - bluebox
        - "{{ local_lab_user }}"
        - docker
      register: addgroups
    - name: Setup user
      become: yes
      user:
        name: "{{ local_lab_user }}"
        group: "{{ local_lab_user }}"
        password: "{{ local_lab_user | password_hash('sha512') }}"
        shell: /bin/bash
        append: yes
        groups:
          - sudo
          - bluebox
          - "{{ local_lab_user }}"
        comment: "bluebox user"
    - name: Set authorized key
      become: yes
      become_user: "{{ local_lab_user }}"
      authorized_key:
        user: "{{ local_lab_user }}"
        key: "{{ lookup('file', '{{ local_lab_user }}-ssh-key.pub') }}"
        state: present
        exclusive: no
        comment: "{{ local_lab_user }}@bluebox.iaas"
      tags: setupkeys
    # - name: Set authorized key
    #   authorized_key:
    #     user: "{{ ansible_user }}"
    #     key: "{{ lookup('file', '{{ local_lab_user }}-ssh-key.pub') }}"
    #     state: present
    #     exclusive: no
    #     comment: "{{ local_lab_user }}@bluebox.iaas"
    #   tags: setupkeys
    - name: Set permissions
      become: yes
      copy:
        content: "{{ local_lab_user }} ALL=(ALL) NOPASSWD:ALL"
        dest: "/etc/sudoers.d/99-bluebox-{{ local_lab_user }}.conf"
    - become: yes
      user:
        name: "{{ local_lab_user }}"
        groups: docker
        append: yes
      ignore_errors: yes
      when: addgroups is not skipped and addgroups is successful

# Prepare IAAS nodes
- hosts: nodes
  become: yes
  pre_tasks:
    - name: "Include vars from: packages.yml"
      include_vars: "{{ lookup('first_found', possible_files) }}"
      vars:
        possible_files:
          - "../packages.yml"
          - "../packages.yaml"
          - "../example.packages.yml"
      tags: 'always'
  tasks:
    - name: Setup node
      include: includes/nodes.yaml
    - name: Setup dependencies
      include: includes/packages.yaml
      tags: ['dep', 'deps', 'dependency']
