---
# ENVIRONMENT - DEPENDENCIES and PACKAGES
- name: Install common-packages
  apt:
    name:
      - htop
      - parallel
      - python-pip
      - python-virtualenv
      - python-setuptools
      - xz-utils
      - tabix
      - autoconf
      - automake
      - make
      - gcc
      - perl
      - zlib1g-dev
      - libbz2-dev
      - liblzma-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libperl-dev
      - libgsl0-dev
- name: Upgrade pip
  pip:
    name: pip
    state: forcereinstall
- name: Install common-packages
  apt:
    name:
      - python3-venv
      - python3-pip
- name: Upgrade pip
  pip:
    name: pip
    state: forcereinstall
    executable: pip3
