extends: default

rules:
  document-start:
    present: false
  indentation:
    # Due to relations from `juju export-bundle`
    indent-sequences: whatever
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    # Allowing 'on' due to: https://github.com/adrienverge/yamllint/issues/158
    allowed-values: ['true', 'false', 'yes', 'no', 'on']
